name: Build Keychron Q0 Max Firmware

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    steps:
    - name: Checkout QMK
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Safe Directory Config
      run: git config --global --add safe.directory /__w/qmk_firmware/qmk_firmware

    - name: Install Dependencies
      run: |
        apt-get update
        apt-get install -y git python3-pip
        pip3 install qmk

    - name: Setup QMK
      run: qmk setup -y

    - name: Compile Firmware
      run: |
        # 다시 올바른 경로(encoder)로 수정했습니다
        qmk compile -kb keychron/q0_max/encoder -km via

    - name: Upload Firmware
      uses: actions/upload-artifact@v4
      with:
        name: keychron_q0_max_firmware
        path: |
          *.bin
          *.hex
